import Papa from "papaparse";

const generateShopifyListingReport = (selectedData) => {
  
    const csvHeaders = [
        "Handle",
        "Title",
        "Body (HTML)",
        "Vendor",
        "Product Category",
        "Type",
        "Tags",
        "Published",
        "Option1 Name",
        "Option1 Value",
        "Option1 Linked To",
        "Option2 Name",
        "Option2 Value",
        "Option2 Linked To",
        "Option3 Name",
        "Option3 Value",
        "Option3 Linked To",
        "Variant SKU",
        "Variant Grams",
        "Variant Inventory Tracker",
        "Variant Inventory Qty",
        "Variant Inventory Policy",
        "Variant Fulfillment Service",
        "Variant Price",
        "Variant Compare At Price",
        "Variant Requires Shipping",
        "Variant Taxable",
        "Variant Barcode",
        "Image Src",
        "Image Position",
        "Image Alt Text",
        "Gift Card",
        "SEO Title",
        "SEO Description",
        "Google Shopping / Google Product Category",
        "Google Shopping / Gender",
        "Google Shopping / Age Group",
        "Google Shopping / MPN",
        "Google Shopping / Condition",
        "Google Shopping / Custom Product",
        "Google Shopping / Custom Label 0",
        "Google Shopping / Custom Label 1",
        "Google Shopping / Custom Label 2",
        "Google Shopping / Custom Label 3",
        "Google Shopping / Custom Label 4",
        "Description (product.metafields.custom.description)",
        "Fabric (product.metafields.custom.fabric)",
        "Fit (product.metafields.custom.fit)",
        "Key Highlights (product.metafields.custom.key_highlights)",
        "Length (product.metafields.custom.length)",
        "Neck (product.metafields.custom.neck)",
        "Occasion (product.metafields.custom.occasion)",
        "Pattern (product.metafields.custom.pattern)",
        "Sleeve (product.metafields.custom.sleeve)",
        "Color (product.metafields.description.color)",
        "Care guide (product.metafields.descriptors.care_guide)",
        "EComposer product countdown end at (product.metafields.ecomposer.countdown)",
        "EComposer product countdown start at (product.metafields.ecomposer.countdown_from)",
        "Google: Custom Product (product.metafields.mm-google-shopping.custom_product)",
        "Product rating count (product.metafields.reviews.rating_count)",
        "Age group (product.metafields.shopify.age-group)",
        "Color (product.metafields.shopify.color-pattern)",
        "Dress occasion (product.metafields.shopify.dress-occasion)",
        "Dress style (product.metafields.shopify.dress-style)",
        "Fabric (product.metafields.shopify.fabric)",
        "Neckline (product.metafields.shopify.neckline)",
        "Size (product.metafields.shopify.size)",
        "Skirt/Dress length type (product.metafields.shopify.skirt-dress-length-type)",
        "Sleeve length type (product.metafields.shopify.sleeve-length-type)",
        "Complementary products (product.metafields.shopify--discovery--product_recommendation.complementary_products)",
        "Related products (product.metafields.shopify--discovery--product_recommendation.related_products)",
        "Related products settings (product.metafields.shopify--discovery--product_recommendation.related_products_display)",
        "Search product boosts (product.metafields.shopify--discovery--product_search_boost.queries)",
        "Variant Image",
        "Variant Weight Unit",
        "Variant Tax Code",
        "Cost per item",
        "Included / India",
        "Price / India",
        "Compare At Price / India",
        "Status"
      ];
      
  
  
  const sizeMapping = {
    XXS: "XXS",
    XS: "XS",
    S: "S",
    M: "M",
    L: "L",
    XL: "XL",
    XXL: "2XL",
    XXXL: "3XL",
    XXXXL: "4XL",
    XXXXXL: "5XL",
  };

  const sizes = Object.keys(sizeMapping); // ["XXS", "XS", "S", "M", "L", "XL", "XXL", "XXXL", "XXXXL", "XXXXXL"]

  const csvData = selectedData.flatMap((product) =>
    sizes.map((size) => {
      const mappedSize = sizeMapping[size]; // Convert size to 2XL, 3XL, etc.
     

   
    //   return {
    //     Handle: product.style_name.trim().toLowerCase().replace(/\s+/g,"-"),
    //     Command: "MERGE",
    //     Title: product.style_name || "",
    //     "Body HTML": product.description ||"",
    //     Vendor: "Qurvii",
    //     Type: product.style_type,
    //     Tags: `Qurvii Women, ${product.color}, ${product.pattern}, women's fashion, casual wear, women's clothing, ${product.style_type}, New Arrivals , New Arrival`,

    //     "Tags Command": "",
    //     Status: "active",
    //     Published: true,
    //     "Published At": "",
    //     "Published Scope": "",
    //     "Template Suffix": "",
    //     "Gift Card": "",
    //     "Category: ID": "",
    //     "Category: Name": "",
    //     Category: "",
    //     "Custom Collections": "",
    //     "Image Attachment": "",
    //     "Image Src": "",
    //     "Image Command": "",
    //     "Image Position": "",
    //     "Title 1": product.style_name || "",
    //     "Variant ID": "",
    //     "Variant Command": "",
    //     "Option1 Name": "SIZE",
    //     "Option1 Value": mappedSize || "",
    //     "Option2 Name": "",
    //     "Option2 Value": "",
    //     "Option3 Name": "",
    //     "Option3 Value": "",
    //     "Variant Generate From Options": "",
    //     "Variant Position": "",
    //     "Variant SKU": `${product.style_number}-${product.color}-${mappedSize}`,
    //     "Variant Weight": 0,
    //     "Variant Weight Unit": "g",
    //     "Variant HS Code": "",
    //     "Variant Country of Origin": "India",
    //     "Variant Province of Origin": "",
    //     "Variant Price": product.mrp,
    //     "Variant Compare At Price": product.mrp,
    //     "Variant Cost": "",
    //     "Variant Requires Shipping": true,
    //     "Variant Taxable": true,
    //     "Variant Tax Code": "",
    //     "Variant Barcode": "",
    //     "Variant Image": "",
    //     "Variant Inventory Tracker": "shopify",
    //     "Variant Inventory Policy": "continue",
    //     "Variant Fulfillment Service": "manual",
    //     "Variant Inventory Qty": 6,
    //     "Variant Inventory Adjust": 0
    //   }


      return{
        Handle: product.style_name.trim().toLowerCase().replace(/\s+/g,"-"),
        "Title":product.style_name || "",
        "Body (HTML)": product.description ||"",
        "Vendor": "Qurvii",
        "Product Category": "",
        "Type":product.type || "",
        Tags: `Qurvii Women, ${product.color}, ${product.pattern}, women's fashion, casual wear, women's clothing, ${product.style_type}, New Arrivals , New Arrival`,
        "Published": "TRUE",
        "Option1 Name": "SIZE",
        "Option1 Value": mappedSize,
        "Option1 Linked To": "",
        "Option2 Name": "",
        "Option2 Value": "",
        "Option2 Linked To": "",
        "Option3 Name": "",
        "Option3 Value": "",
        "Option3 Linked To": "",
        "Variant SKU": `${product.style_number}-${product.color}-${mappedSize}`,
        "Variant Grams": "",
        "Variant Inventory Tracker": "shopify",
        "Variant Inventory Qty": "6",
        "Variant Inventory Policy": "continue",
        "Variant Fulfillment Service": "manual",
        "Variant Price": product.mrp,
        "Variant Compare At Price": product.mrp,
        "Variant Requires Shipping": "TRUE",
        "Variant Taxable": "TRUE",
        "Variant Barcode": "",
        "Image Src": "",
        "Image Position": "",
        "Image Alt Text": "",
        "Gift Card": "",
        "SEO Title": "",
        "SEO Description": "",
        "Google Shopping / Google Product Category": "",
        "Google Shopping / Gender": "",
        "Google Shopping / Age Group": "",
        "Google Shopping / MPN": "",
        "Google Shopping / Condition": "",
        "Google Shopping / Custom Product": "",
        "Google Shopping / Custom Label 0": "",
        "Google Shopping / Custom Label 1": "",
        "Google Shopping / Custom Label 2": "",
        "Google Shopping / Custom Label 3": "",
        "Google Shopping / Custom Label 4": "",
        "Description (product.metafields.custom.description)": product.description,
        "Fabric (product.metafields.custom.fabric)": product.fabric,
        "Fit (product.metafields.custom.fit)": product.fit || "",
        "Key Highlights (product.metafields.custom.key_highlights)": `${product.season}`,
        "Length (product.metafields.custom.length)": product.sleeve_length_type ||"",
        "Neck (product.metafields.custom.neck)":product.neckline ||"",
        "Occasion (product.metafields.custom.occasion)": product.occasion || "",
        "Pattern (product.metafields.custom.pattern)": product.pattern || "",
        "Sleeve (product.metafields.custom.sleeve)": "",
        "Color (product.metafields.description.color)": product.color || "",
        "Care guide (product.metafields.descriptors.care_guide)": product.care_instruction,
        "EComposer product countdown end at (product.metafields.ecomposer.countdown)": "",
        "EComposer product countdown start at (product.metafields.ecomposer.countdown_from)": "",
        "Google: Custom Product (product.metafields.mm-google-shopping.custom_product)": "",
        "Product rating count (product.metafields.reviews.rating_count)": "",
        "Age group (product.metafields.shopify.age-group)": "",
        "Color (product.metafields.shopify.color-pattern)": "",
        "Dress occasion (product.metafields.shopify.dress-occasion)": "",
        "Dress style (product.metafields.shopify.dress-style)": "",
        "Fabric (product.metafields.shopify.fabric)": product.fabric,
        "Neckline (product.metafields.shopify.neckline)": product.neckline ||"",
        "Size (product.metafields.shopify.size)": mappedSize ||"",
        "Skirt/Dress length type (product.metafields.shopify.skirt-dress-length-type)": "",
        "Sleeve length type (product.metafields.shopify.sleeve-length-type)": product.sleeve_length_type,
        "Complementary products (product.metafields.shopify--discovery--product_recommendation.complementary_products)": "",
        "Related products (product.metafields.shopify--discovery--product_recommendation.related_products)": "",
        "Related products settings (product.metafields.shopify--discovery--product_recommendation.related_products_display)": "",
        "Search product boosts (product.metafields.shopify--discovery--product_search_boost.queries)": "",
        "Variant Image": "",
        "Variant Weight Unit": "",
        "Variant Tax Code": "",
        "Cost per item": "",
        "Included / India": "",
        "Price / India": "",
        "Compare At Price / India": "",
        "Status": "active"
      };
      
    })
  );

    

  const csv = Papa.unparse({
    fields: csvHeaders,
    data: csvData,
  });

  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = "Shopify_Listing.csv";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export { generateShopifyListingReport };
